### ISSUE TITLE
Edit Blog options

### ISSUE THREAD

**Issue by juanpduke** [godaddy-wordpress/primer-child-uptownstyle#33]
Hi, Im using the uptown style theme, and have 2 questions
1. How can I choose where the "continue reading" button appears?
![image](https://user-images.githubusercontent.com/31603711/30008780-53ea2684-90e8-11e7-883b-9ea4da607a1f.png)
I mean , I want to see at least the first paragraph of the article and then, the continue reading button.

2. Once inside the article, I want to remove the Header image

![image](https://user-images.githubusercontent.com/31603711/30008815-a6667750-90e8-11e7-830b-cf70b993afea.png)

Thanks for the answers

**Comment by EvanHerman** [comment]
Hi @juanpduke 

It's not possible to manually select where that read more link appears. You would need to use a bit of coding to remove the hook and re-add it at a location of your choosing.

Inside of the article you can remove the header image through CSS. If you have a link to that page, I would be happy to help point you in the right direction.

**Comment by marcocaridad** [comment]
Hi!

I am designing the following website: http://hispafest.net/ But my theme doesn't have the option for a portfolio.

The uncategorized posts I am redirecting to the news and I am good with that. However, they want me to add their picture events, so I need to create their portfolio.

Any idea how can I solve this issue?


<img width="765" alt="Screen Shot 2020-04-21 at 8 58 33 AM" src="https://user-images.githubusercontent.com/6798608/79868724-56153500-83ae-11ea-8e38-71ed194945e7.png">

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
