### ISSUE TITLE
CHANGE LOGO SIZE HEADER AND ALIGNMENT

### ISSUE THREAD

**Issue by colorplus2020** [godaddy-wordpress/primer-child-uptownstyle#42]
Hello there, When uploading the logo, it's huge, the theme does not re-size it automatically, and I can not align it to any side, right or left. please help asap. Thx

![whatsapp image 2019-01-25 at 9 44 29 am](https://user-images.githubusercontent.com/47033594/51752649-fa161080-2085-11e9-9de8-49e94034a3b6.jpeg)

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
