### ISSUE TITLE
Menu on mobile

### ISSUE THREAD

**Issue by Sandiedog** [godaddy-wordpress/primer-child-uptownstyle#44]
The menu is not showing up correctly on mobile (dropdowns are hidden behind an image I put on the home page) and they are not live links. Any ideas?

**Comment by jdifalco** [comment]
Hello, I am just now seeing this error on my site. @Sandiedog did you ever fix your issue?

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
