### ISSUE TITLE
Duplicate Menu Locations

### ISSUE THREAD

**Issue by FootZoner** [godaddy-wordpress/primer-child-uptownstyle#45]
I wanted to add a menu so guests could login to WordPress.  I added the login link to a Social menu (labeled as top menu) thinking it would be at the top of the page.  It was below the footer and showed up (originally) as an icon.  I decided to change the location to a Footer menu and added it to a widget.  The menu now shows up in both locations except now the menu link that is below the footer isn't an icon, it's text.  I've cleared cache and it still shows up in both places.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
