### ISSUE TITLE
Button Link

### ISSUE THREAD

**Issue by FootZoner** [godaddy-wordpress/primer-child-uptownstyle#46]
I'm not sure if this is a theme issue or a Beaver Builder issue.  I added a call to action button via Beaver Builder.  When first added, the link worked fine, then is stopped working.  The button links to:
FindaFootZoner.com/login, however the button directs viewers to FindaFootZoner.com/directory/FindaFootZoner.com/login and shows Ooops!  This page doesn't exist when the button is clicked.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
